[build]
  base = "/"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "22"

# Production context: all deploys from the main branch
[context.production]
  command = "npm run vite:build"

# Redirects and headers are GLOBAL for all builds
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  values = { Cache-Control = "public, max-age=31536000, immutable" }

[[headers]]
  for = "/*.js"
  values = { Cache-Control = "public, max-age=31536000, immutable" }

[[headers]]
  for = "/*.css"
  values = { Cache-Control = "public, max-age=31536000, immutable" }

[[headers]]
  for = "/index.html"
  values = { Cache-Control = "public, max-age=0, must-revalidate" }
