[build]
  base = "." # Use current directory as base
  publish = "dist"
  command = "bash netlify-build.sh"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"  # Use a more stable version
  VITE_SUPABASE_URL = "https://bjpjorklchrtcpbfzvtv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcGpvcmtsY2hydGNwYmZ6dnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTE5NjAsImV4cCI6MjA2NDE4Nzk2MH0.40JtFzHr46Ps83nZbhQSO7q7o0H_o_gRwVF_YeM3wYo"

# Production context: all deploys from the main branch
[context.production]
  command = "npm run netlify:clean-build"

# Deploy settings - automatically deploy from main branch
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Redirects and headers are GLOBAL for all builds
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# --- Netlify headers for optimal SPA caching ---
# 1. Never cache index.html (always fetch latest shell)
[[headers]]
  for = "/index.html"
  values = { Cache-Control = "no-cache, no-store, must-revalidate" }

# 2. Aggressively cache static assets (JS, CSS, etc.)
[[headers]]
  for = "/*.js"
  values = { Cache-Control = "public, max-age=31536000, immutable" }

[[headers]]
  for = "/*.css"
  values = { Cache-Control = "public, max-age=31536000, immutable" }

[[headers]]
  for = "/assets/*"
  values = { Cache-Control = "public, max-age=31536000, immutable" }

# 3. Optionally cache all other files long-term except index.html
[[headers]]
  for = "/*"
  values = { Cache-Control = "public, max-age=31536000, immutable" }
