import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/holographic.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" data-oid="6vt9iqt">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased futuristic-theme`}
        data-oid="hbs14z7"
      >
        <nav
          className="py-4 bg-slate-900 bg-opacity-50 text-center"
          data-oid="l_dtzkc"
        >
          <a
            href="/"
            className="holographic-text px-4"
            data-text="Home"
            data-oid="ori62.4"
          >
            Home
          </a>
          <a
            href="/admin"
            className="holographic-text px-4"
            data-text="Admin"
            data-oid="26v6420"
          >
            Admin
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
